version: 2
jobs:
  node8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-npm-deps-
      - run: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run lint
      - run: npm test
      - run: npm run build
  node10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-npm-deps-
      - run: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run lint
      - run: npm test
      - run: npm run build
  docs:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm run generate-docs
      - run:
          command: |
            npm run generate-docs
            git checkout docs
            mv docs/* .
            rm -rf docs/ classes/ enums/ interfaces/ README.md
            ls -la
workflows:
  version: 2
  run_pipeline:
    jobs:
      - node8
      - node10
      - docs:
          requires:
            - node8
            - node10
