version: 2
jobs:
  node8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-npm-deps-
      - run: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run lint
      - run: npm test
      - run: npm run build
  node10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-npm-deps-
      - run: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run lint
      - run: npm test
      - run: npm run build
  docs:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-npm-deps-
      - run: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Generate docs
          command: |
            npm run generate-docs
            git reset --hard
            cp README.md /tmp
            git checkout gh-pages
            rm -rf node_modules/
            shopt -s extglob
            echo !(.|..|.git|_config.yml)
            rm -rf classes/ enums/ interfaces/ README.md
            mv docs/* .
            mv /tmp/README.md .
            rmdir docs
      - deploy:
          name: Deploy docs
          command: |
            git diff-index --quiet HEAD -- && echo "No changes in docs, no need to deploy." && exit 0
            echo "Detected changes in docs, deploying new docs version."
            git config credential.helper 'cache --timeout=120'
            git config user.name "${GITHUB_NAME}"
            git config user.email "${GITHUB_EMAIL}"
            git add .
            git commit -m "docs: Automatic generation"
            echo "Pushing to gh-pages branch..."
            git push -q https://${GITHUB_TOKEN}@github.com/Dabolus/nodejs-assistant.git gh-pages
workflows:
  version: 2
  run_pipeline:
    jobs:
      - node8:
          filters:
            branches:
              only: master
      - node10:
          filters:
            branches:
              only: master
      - docs:
          filters:
            branches:
              only: master
          requires:
            - node8
            - node10
