version: 2
jobs:
  node8:
    docker:
      - image: node:8-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-npm-deps-
      - run: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run lint
      - run: npm test
      - run: npm run build
  node10:
    docker:
      - image: node:10-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-npm-deps-
      - run: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run lint
      - run: npm test
      - run: npm run build
workflows:
  version: 2
  run_pipeline:
    jobs:
      - node8
      - node10
